image: golang:1.8
stages:
  - test
  - build
  - image

build:
  stage: build
  before_script:
    - go get github.com/tools/godep
    - cp -r /builds/rodrigodealer /go/src/github.com/rodrigodealer/
    - cd /go/src/github.com/rodrigodealer/users
  script:
    - godep restore
    - godep go build

test:
  stage: test
  services:
    - redis:latest
  before_script:
    - go get github.com/tools/godep
    - cp -r /builds/rodrigodealer /go/src/github.com/rodrigodealer/
    - cd /go/src/github.com/rodrigodealer/users
  script:
    - godep restore
    - godep go test -v -cover ./...

docker_build:
  only:
  - master
  stage: image
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker run --rm -e APP_BIN=users -e APP_PATH=/go/src/github.com/rodrigodealer/users -v $PWD:/go/src/github.com/rodrigodealer/users rodrigodealer/go-builder:latest
    - docker build . -t registry.gitlab.com/rodrigodealer/users:latest
    - docker push registry.gitlab.com/rodrigodealer/users:latest
